### ISSUE TITLE
Error with -altmodel

### ISSUE THREAD

**Issue by rainbowcnh** [mwaskom/lyman#79]
Hi,

I was getting an error with the command:
 run_fmri.py -w model -altmodel non

Below is the error message:

150913-22:21:36,662 workflow INFO:
	 Traceback (most recent call last):
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/nipype-0.10.0-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/nipype-0.10.0-py2.7.egg/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/nipype-0.10.0-py2.7.egg/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/nipype-0.10.0-py2.7.egg/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/nipype-0.10.0-py2.7.egg/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/lyman/workflows/model.py", line 190, in _run_interface
    self.design_report(self.inputs.exp_info, X, design_kwargs)
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/lyman/workflows/model.py", line 270, in design_report
    X.plot_confound_correlation(fname=corr_png, close=True)
  File "/Users/cnh/anaconda/lib/python2.7/site-packages/moss/glm.py", line 590, in plot_confound_correlation
    lgd = ax.legend(bars, self._confound_names, ncol=ncol, fontsize=10,
UnboundLocalError: local variable 'bars' referenced before assignment

It seems that the design matrix of the alternative model was not generated... Could you help me fix this error? Thanks.

**Comment by rainbowcnh** [comment]
It is solved after removing the comma at the end of each line in the <design_file>.csv. The code might be improved to increase compatibility...
