### ISSUE TITLE
Changes in IPython parallel cause an error when there is an error in make_masks

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/lyman#83]
Yo dawg.

Errors within `make_masks.py` are no longer propagated correctly

``` python
Traceback (most recent call last):
  File "/home/mwaskom/anaconda/bin/make_masks.py", line 259, in <module>
    main(sys.argv[1:])
  File "/home/mwaskom/anaconda/bin/make_masks.py", line 66, in main
    proj_args, args.save_native)
  File "/home/mwaskom/anaconda/lib/python2.7/site-packages/lyman/maskfactory.py", line 142, in from_common_label
    self.from_native_label(native_label_temp, hemis, proj_args)
  File "/home/mwaskom/anaconda/lib/python2.7/site-packages/lyman/maskfactory.py", line 165, in from_native_label
    self.execute(proj_cmds, indiv_mask_temp)
  File "/home/mwaskom/anaconda/lib/python2.7/site-packages/lyman/maskfactory.py", line 283, in execute
    raise RuntimeError(res.pyerr)
  File "/home/mwaskom/anaconda/lib/python2.7/site-packages/IPython/parallel/client/asyncresult.py", line 267, in __getattr__
    self.__class__.__name__, key))
AttributeError: 'AsyncMapResult' object has no attribute 'pyerr'
```

Also in general the parallel machinery should be updated to use the right namespace.

**Comment by mwaskom** [comment]
Closing as there is not more `make_masks.py` (though I think this was fixed in 1.0).
