### ISSUE TITLE
lyman .08 issue

### ISSUE THREAD

**Issue by iancballard** [mwaskom/lyman#87]
Recently updated to the latest version from git and am running into an error when running the preproc workflow. I can't recreate it outside of the lyman workflow: nib.load works fine on the functional_mask.nii.gz file produced by convertmask. I tried uninstalling nibabel and updating to the most recent version, and also reset permissions on all the relevant folders. Any ideas?

```
S'Traceback (most recent call last):\n'
p207
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node\n    result[\'result\'] = node.run(updatehash=updatehash)\n'
p208
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1428, in run\n    self._run_interface()\n'
p209
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1538, in _run_interface\n    self._result = self._run_command(execute)\n'
p210
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1664, in _run_command\n    result = self._interface.run()\n'
p211
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1033, in run\n    runtime = self._run_wrapper(runtime)\n'
p212
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 983, in _run_wrapper\n    runtime = self._run_interface(runtime)\n'
p213
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/lyman/workflows/preproc.py", line 916, in _run_interface\n    self.plot_mean_image()\n'
p214
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/lyman/workflows/preproc.py", line 926, in plot_mean_image\n    self.inputs.mask_file, step=1)\n'
p215
aS'  File "/home/iballard/.local/lib/python2.7/site-packages/moss/mosaic.py", line 86, in __init__\n    mask_img = nib.load(mask)\n'
p216
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/loadsave.py", line 44, in load\n    return guessed_image_type(filename).from_filename(filename, **kwargs)\n'
p217
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/keywordonly.py", line 16, in wrapper\n    return func(*args, **kwargs)\n'
p218
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/freesurfer/mghformat.py", line 528, in from_filename\n    return klass.from_file_map(file_map, mmap=mmap)\n'
p219
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/keywordonly.py", line 16, in wrapper\n    return func(*args, **kwargs)\n'
p220
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/freesurfer/mghformat.py", line 494, in from_file_map\n    header = klass.header_class.from_fileobj(mghf)\n'
p221
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/freesurfer/mghformat.py", line 192, in from_fileobj\n    return klass(hdr_str + ftr_str, check)\n'
p222
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/freesurfer/mghformat.py", line 110, in __init__\n    hdr = self._set_affine_default(hdr)\n'
p223
aS'  File "/home/iballard/anaconda/lib/python2.7/site-packages/nibabel/freesurfer/mghformat.py", line 409, in _set_affine_default\n    hdr[\'delta\'][:] = np.array([1, 1, 1])\n'
p224
aS'ValueError: assignment destination is read-only\nInterface MaskReport failed to run. \n'
```

**Comment by iancballard** [comment]
looking like it's probably not lyman. Adding         

hdr = hdr.copy()

to the first line of the _set_affine_default(self, hdr) function in mghformat.py in nibabel seems to fix it. Still curious if you have come accross this issue.

**Comment by mwaskom** [comment]
haven't seen it. what version nibabel

**Comment by iancballard** [comment]
2.0.2

**Comment by mwaskom** [comment]
That is what I have IIRC but haven't seen this. Note though that the latest lyman version should be "0.0.10.dev"?

**Comment by iancballard** [comment]
Yeah I just cloned again today (lyman==0.0.10.dev0). What a mystery. I hacked an ugly solution to the Mosaic problem for the time being. I'll let you know if I track down what's happening.
